### ISSUE TITLE
Flashing firmware 0.3.2 stuck at empty settings

### ISSUE THREAD

**Issue by BillyBuerger** [ahtn/keyplus#71]
I flashed the latest firmware 0.3.2 on my Keyplus Rev03 and it appears to flash fine but the info states "Warning: Empty settings!"  Every time I've flashed the firmware I end up with a device ID set to 255.  So I go to Device and RF, pick a layout file and set Device id to 0 and generate a new RF settings, then program.  This time I get an error "'encoding' is an invalid keyword argument for this function".  I am able to flash back to firmware 0.3.1 without any issues and get it back working again.

![keyplus0 3 2firmwareerror](https://user-images.githubusercontent.com/23403977/40095047-a4f0bf74-588f-11e8-9cb3-0355c0d6de1d.png)

**Comment by angustrau** [comment]
The device settings resetting every time you flash is an unfortunate side effect of keyplus storing its settings in the flash section of the xmega instead of eeprom.

The `'encoding' is an invalid keyword argument for this function` error is likely because Python 2 (which the Windows version of the flasher is built with) version of `open()` [doesn't support the `encoding` argument](https://docs.python.org/2/library/functions.html#open) introduced [in this commit](https://github.com/ahtn/keyplus/commit/dff4ac9cd8de4384829830e38b7012f68e4cc3c1#diff-14ec0fd69cc43e190c92bcf013139160L55).

**Comment by angustrau** [comment]
Try using [this build](https://ci.keyplus.io/job/keyplus-flasher-angustrau/lastSuccessfulBuild/artifact/keyplus/host-software/dist/keyplus_flasher-0.3.2-c084625-build5.exe).

**Comment by angustrau** [comment]
Hmm. You should be able to download it from [here](https://ci.keyplus.io/job/keyplus-flasher/)

**Comment by angustrau** [comment]
This appears to be a bug with Keyplus Flasher's port to PyQt5. It seems to be fixed in the latest build from Keyplus CI.

**Comment by BillyBuerger** [comment]
Thanks, that did it.  I was able to flash the 3.3 firmware without issue.  And now my volume keys are working.  Thanks for the hard work.
